### ISSUE TITLE
Sending environment variable?

### ISSUE THREAD

**Issue by irsooti** [appleboy/telegram-action#1]
Hello,
is there a way to send an environment variable as an argument? I tried like:

```
`echo $GITHUB_SHA` blabla message
```
But doesn't work :(

**Comment by appleboy** [comment]
@irsooti 

```
action "Send Custom Message" {
  uses = "appleboy/telegram-action@master"
  secrets = [
    "TELEGRAM_TOKEN",
    "TELEGRAM_TO",
  ]
  args = "A new commit has been pushed. commit: {{ commit.sha }}"
}
```

I will update the document.

**Comment by appleboy** [comment]
@irsooti See the doc: https://github.com/appleboy/telegram-action#template-variable

**Comment by maslick** [comment]
I need to send a link to the build results
```
GITHUB_WORKFLOW_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
```

```
- uses: appleboy/telegram-action@master
  with:
    to: ${{ secrets.TELEGRAM_TO }}
    token: ${{ secrets.TELEGRAM_TOKEN }}
    message: Success! See build details at https://github.com/${{ repo }}/actions/runs/${{ github.github_run_id }}
  name: send Telegram message
```

I can get the repo using your template variables. Can you make the GITHUB_EVENT_NAME env variable available through templates? Thanks

**Comment by danielo515** [comment]
The `${{ repo }}` one gives an error on github because it doesn't know what it is

**Comment by elhmn** [comment]
I wrote an action that gets some data from the github  api and I would like to send them in a message to telegram.
I did that by storing the data in an environment variable and tried to use that env variable in the message field but it does not seem to work.

Here is what I am doing it :

```yaml
    steps:
    - uses: actions/checkout@master
    - name: get yotas issues
      working-directory: ./.github/workflows/recommend_yotas_issues
      shell: bash
      run: |
          GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} ./get_yotas_issues.sh > yotas_issues_message \
          && echo 'YOTAS_ISSUES_MESSAGE <<EOF' >> $GITHUB_ENV
          cat yotas_issues_message >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: ${{ env.YOTAS_ISSUES_MESSAGE }}
```
