### ISSUE TITLE
missing telegram token or user list

### ISSUE THREAD

**Issue by sa-esmaili** [appleboy/telegram-action#10]
I'm getting this error and action fails:
```missing telegram token or user list```

Here is my yml file:
```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            An event occured in ${{ github.repository	 }} repository.
            ${{ github.event_name }}
```
I quite new in Github Actions. What should I do to fix this? 
P.S: I've added telegram_token and telegram_chat_id to secrets section of repo.
