### ISSUE TITLE
A commit message with a comma will send multiple messages

### ISSUE THREAD

**Issue by obayit** [appleboy/telegram-action#14]
I have this commit message:
`[FIX] hr_operations: readd missing imports`
The bot sent separate messages:
![IMG_20200617_125924](https://user-images.githubusercontent.com/20386024/84890752-18c1e080-b09b-11ea-873e-8ebcdf316dc7.jpg)

Here is my workflow yml file:
```
name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: ${{ github.actor }}:${{ github.event.head_commit.message }}

```

**Comment by appleboy** [comment]
@appleboy replace `args` with `message`

**Comment by obayit** [comment]
I tried using `message`, doesn't work

**Comment by appleboy** [comment]
I will try it.

**Comment by aszenz** [comment]
Facing this same issue for comma's in message, also messages can't be interpolated with variables:
```
uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TO }}
          token: ${{ secrets.TOKEN }}
          format: html
          message: |
            ⚡️ <a href="https://github.com/aszenz/repo/commit/${{ github.event.push.after }}">Commits</a> pushed to master by <em>${{ github.event.push.pusher.name }}</em>,<a href="https://github.com/aszenz/repo/pull/${{ steps.set-variables.outputs.pr_no }}">PR</a> ⚡️
```
Results in two separate messages 
```
⚡️ Commits (https://github.com/aszenz/repo/commit/) pushed to master by

PR (https://github.com/aszenz/qbil-trade/pull/) ⚡️
```
