### ISSUE TITLE
Error when sending Unexpected input(s) 'if'

### ISSUE THREAD

**Issue by Resmedia** [appleboy/telegram-action#18]
Hello! 

I got problem today with sending, before all was fine.

My yml

```
name: telegram message
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
    
    #Request
     - name: Telegram Notify request
       if: ${{ github.event_name == 'pull_request' }}
       uses: appleboy/telegram-action@v0.0.8
       with:
         to: ${{ secrets.CHAT }}
         token: ${{ secrets.TOKEN }}
         args: User ${{github.actor}} in ${{ github.repository }} repository. Make ${{ github.event_name }}. Job ${{github.job}} URL - "${{ github.event.pull_request.title }} --> ${{ github.event.pull_request.html_url }}"
    
    #Push  
     - name: Telegram Notify push
       if: ${{ github.event_name == 'push' }}
       uses: appleboy/telegram-action@v0.0.8
       with:
         to: ${{ secrets.CHAT }}
         token: ${{ secrets.TOKEN }}
         args: User ${{github.actor}} in ${{ github.repository }} repository. Make ${{ github.event_name }}. Job ${{github.job}} URL - "${{ github.event.head_commit.message }} --> ${{ github.event.head_commit.url }}"
```

Errors:

<img width="1344" alt="Снимок экрана 2020-07-19 в 11 18 49" src="https://user-images.githubusercontent.com/9871970/87870534-a867f100-c9b1-11ea-86e3-e28315f6d681.png">

and 

<img width="1338" alt="Снимок экрана 2020-07-19 в 11 19 37" src="https://user-images.githubusercontent.com/9871970/87870553-c6355600-c9b1-11ea-8e9c-f43eecf53ce4.png">

Is there something wrong with me?
