### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by aoii103** [appleboy/telegram-action#19]
I got this error when do this
```
with:
    to: ***
    token: ***
    message: sharingan report
    message_file: ./events/ruanyf/ruanyf.json
```
