### ISSUE TITLE
Commit message is not printing

### ISSUE THREAD

**Issue by alphastorm** [appleboy/telegram-action#21]
I'm using the following YAML config (which I copied from https://github.com/appleboy/telegram-action/issues/14):

```
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          😍 A pull request has been merged on GitHub!
          ${{ github.actor }}: ${{ github.event.head_commit.message }}
```

However, the commit message isn't printing properly.  Any idea what I'm doing wrong?  Thanks for your help!

**Comment by hkpanchani** [comment]
It does gets printed..
Check my workflow here => https://github.com/hkpanchani/pipelines/blob/master/telegramNotification.yml

**Comment by appleboy** [comment]
See the commit https://github.com/appleboy/telegram-action/commit/6ecbcc43b08e6989fa823b70b488ffa963be411e

```yaml
    - name: send message useing with
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          The ${{ github.event_name }} event triggered second step.
          show the github varable ref: ${{ github.ref }}
          show the github varable commit: ${{ github.sha }}
          show the github varable ref: {{ commit.ref }}
          show the github varable commit: {{ commit.sha }}
          Commit Message: ${{ github.event.head_commit.message }}
```
