### ISSUE TITLE
how to disable web previews?

### ISSUE THREAD

**Issue by genemators** [appleboy/telegram-action#23]

**Comment by MarcMogdanz** [comment]
Currently not possible, as this repo is using the author's [drone-telegram](https://github.com/appleboy/drone-telegram) docker image you can possibly create an issue over there :)

**Comment by appleboy** [comment]
@MarcMogdanz @genemators I will take it.

**Comment by appleboy** [comment]
See https://github.com/appleboy/telegram-action/releases/tag/v0.0.9

```yaml
    - name: link preview
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          link preview https://google.com.tw

    - name: disable link preview
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        webpage_preview: false
        message: |
          link preview https://google.com.tw
```

**Comment by appleboy** [comment]
@MarcMogdanz @genemators 

See https://github.com/appleboy/telegram-action/releases/tag/v0.1.0

```yaml
    - name: link preview
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          show link preview https://google.com.tw

    - name: disable link preview
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        message: |
          disable link preview https://google.com.tw
```
