### ISSUE TITLE
unable to access artifact for message document

### ISSUE THREAD

**Issue by chunlee-thong** [appleboy/telegram-action#32]
this is my action script:

```
name: Send apk to Telegram group
on:
  push:
    branches:
      - dev
jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.5"
      - run: flutter pub get
      - run: flutter build apk --release --flavor dev
      - name: Build artifact APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-file
          path: build/app/outputs/flutter-apk/app-dev-release.apk

  send_to_telegram:
    name: Send Apk to Asurraa telegram group
    needs: build_apk
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-file
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/checkout@master
      - name: send apk file
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{github.event.head_commit.message}}
          document: app-dev-release.apk
```

the message is sent the not the document
