### ISSUE TITLE
Send message to group

### ISSUE THREAD

**Issue by w3k5** [appleboy/telegram-action#37]
Hi there!
Have one problem, I created bot and configured to send messages into my chat, but I want make notification to group.
Group has ID with - and action doesn't work.
Is it bug or I'm doing something wrong?

My yaml
``` 
     - name: Telegram Notify Success
        uses: appleboy/telegram-action@master
        if: ${{ success() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ *The job has been completed.*
            #️⃣ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            🧑‍💻 Developer: *${{github.actor}}*
            🔗 Href: https://github.com/${{github.repository}}
          format: markdown
          disable_web_page_preview: "True"
      - name: Telegram Notify Failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ *The job has been failed!*
            #️⃣ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            🧑‍💻 Developer: *${{github.actor}}*
            🔗 Href: https://github.com/${{github.repository}}
          format: markdown
          disable_web_page_preview: "True"
          ```
