### ISSUE TITLE
Clarify Markdown vs MarkdownV2 support

### ISSUE THREAD

**Issue by shardwolfdotnet** [appleboy/telegram-action#45]
The [docs](https://github.com/appleboy/telegram-action#input-variables) mention MarkdownV2 support, but based on my own tests it appears that only legacy Markdown syntax is supported.

For example, see the following actions snippet:
```yaml
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR ${{ github.event.number }}:
            [_${{ github.event.pull_request.title }}_](${{ github.event.pull_request.html_url }})
          format: markdown
```
Despite not being escaped, the italicized title didn't work as expected:
![image](https://user-images.githubusercontent.com/76196468/157163429-bee8dbb3-c98a-497c-a935-71e61dbcdcf1.png)

The [markdown style](https://core.telegram.org/bots/api#markdown-style) notes mention this:
> Entities must not be nested, use parse mode [MarkdownV2](https://core.telegram.org/bots/api#markdownv2-style) instead.

Moreover, [drone-telegram](https://github.com/appleboy/drone-telegram/blob/master/DOCS.md#parameter-reference) seems to indicate `markdown` (v1) is the supported Markdown flavor - not v2.

Can the docs get updated to indicate which flavor of markdown is actually supported?
