### ISSUE TITLE
Possibility to specify an array of `chat_id`s

### ISSUE THREAD

**Issue by AmirABody** [appleboy/telegram-action#47]
Hello there, Hope everything is fine as always.

I thought that it would be interesting if we could have the possibility of giving an array of `chat_id`s (so-called `to` arg) in the action, thus we are able to send one message to several chats in one step. and I really doubt that implementation of this feature would be even difficult or time-consuming.

A sample of what I'm considering:

```
name: telegram message
on: [<any>]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: [${{ secrets.TELEGRAM_TO1 }}, ${{ secrets.TELEGRAM_TO2 }}, ${{ secrets.TELEGRAM_TO3 }}]
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: A Telegram Message:)
```

I would be grateful if we could have that on the subsequent release. :blush:
