### ISSUE TITLE
No message sent

### ISSUE THREAD

**Issue by RdeWilde** [appleboy/telegram-action#5]
I am trying to use this action on the event of creating a new issues. The workflow is started, but not message is received. I created te bot, invited it to the channel, got the right token for it, gave it enough permission in channel... but no messages are being sent

What is the problem?

I am using a public group, so I am using the `@handle` as `TELEGRAM_TO`. I tried both with and without `@`.
```
Run appleboy/telegram-action@master
  with:
    message: The issues event triggered final step.
  
  env:
    TELEGRAM_TOKEN: ***
    TELEGRAM_TO: ***
/usr/bin/docker run --name dd9e735ca8d921d65548c3a93faf9a141f4d99_72c96d --label dd9e73 --workdir /github/workspace --rm -e TELEGRAM_TOKEN -e TELEGRAM_TO -e INPUT_MESSAGE -e INPUT_PHOTO -e INPUT_DOCUMENT -e INPUT_STICKER -e INPUT_AUDIO -e INPUT_VOICE -e INPUT_LOCATION -e INPUT_VENUE -e INPUT_VIDEO -e INPUT_DEBUG -e INPUT_FORMAT -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/paycoin/paycoin":"/github/workspace" dd9e73:5ca8d921d65548c3a93faf9a141f4d99
```
