### ISSUE TITLE
How to send photo as link

### ISSUE THREAD

**Issue by Dudoserovich** [appleboy/telegram-action#55]
Hello!
I want to send a picture generated by api, but the bot just skips the code section with sending a photo if I specify a link ((
I tried to specify the link both in quotes and without

Example code:
```yml
name: telegram message
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: hello
          photo: https://cataas.com/cat
          document: https://cataas.com/cat
```
