### ISSUE TITLE
Add support for sending messages to Topics

### ISSUE THREAD

**Issue by faizanakram99** [appleboy/telegram-action#57]
Messages can be send to topics by `reply_to_message_id` parameter (with the message id with which topic was created)

**Comment by divineforge** [comment]
upvote this feature too.

**Comment by pompushko** [comment]
+1

**Comment by kungfu321** [comment]
+1

**Comment by Chris-CBQA** [comment]
+1

**Comment by ForAeons** [comment]
+1

**Comment by shukhratutaboev** [comment]
+1

**Comment by muradddd** [comment]
+1

**Comment by iomonad** [comment]
This feature is really needed :+1:

**Comment by MarkParker5** [comment]
+1
Are there any updates or alternatives?

**Comment by muradddd** [comment]
> +1 Are there any updates, forks, or alternatives?

@MarkParker5, you can use Telegram's API.

**Comment by MarkParker5** [comment]
> > +1 Are there any updates, forks, or alternatives?
> 
> @MarkParker5, you can use Telegram's API.

Already. There is an example:

```yml
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      run: |
        msg_text='Your message text here'
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TOKEN }}/sendMessage' \
        -d "chat_id=${{ secrets.CHAT_ID }}&text=${msg_text}&reply_to_message_id=${{ secrets.MSG_ID }}"
```
