### ISSUE TITLE
Markdown escaping issue

### ISSUE THREAD

**Issue by rc5hack** [appleboy/telegram-action#58]
This job step always fails:

```yaml
    - name: Send telegram notification
      if: ${{always()}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{secrets.TELEGRAM_CHAT}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        format: markdown
        message: |
          Test *()
```

Job logs:
```
Run appleboy/telegram-action@master
  with:
    to: ***
    token: ***
    format: markdown
    message: Test *()
  
  env:
    ...
/usr/bin/docker run --name dc5057a2652147a674d62abf3a4930e7521c7_f86794 --label 0dc505 --workdir /github/workspace --rm -e ...
2023/10/22 18:39:40 Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 5
```

Should I manually escape chars in `message`?
