### ISSUE TITLE
can't use $GITHUB_OUTPUT?

### ISSUE THREAD

**Issue by alanhe421** [appleboy/telegram-action#68]
```yml
      echo discussionCount=$COUNT >> $GITHUB_OUTPUT

```

steps.repo-discussion.outputs.discussionCount not work.

```yml
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            There are currently ${{steps.repo-discussion.outputs.discussionCount}} discussions, come on!
          format: markdown
```
